name: 'Deploy'
on:
  push:
    branches:
      - develop
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
  runs-on: ubuntu-latest
    steps:
      - uses: natete/workflows-test/.github/workflows/build.yml@main
        if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        with:
          java_version: 17
        secrets: inherit
