name: 'Deploy'
on:
  push:
    branches:
      - develop
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    uses: natete/workflows-test/.github/workflows/build.yml@main
      with:
        java_version: 17
      secrets: inherit
