name: 'Deploy'
on:
  push:
    branches:
      - develop
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: natete/workflows-test/.github/workflows/build.yml@main
    with:
      java_version: 17
      nexus_user: "nexus_user"
      nexus_password: "nexus_pass"
      branch: ${{ github.base_ref }}
    secrets: inherit
